theme: jekyll-theme-minimal
title: syllabus of a weird wide web.
description: this is it. a destination pointing to the useful resources across the web. please share. 

all tools are what they are. i did not fully check their origin, i am not maintaining them. everything you enter there, could be read by a third party. so please don't upload your full product roadmap to compress pdf. 
